from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
from PySide2 import QtWidgets


class Ui_tela_alterar_dados(object):
    def setupUi(self, tela_alterar_dados):
        if not tela_alterar_dados.objectName():
            tela_alterar_dados.setObjectName(u"tela_alterar_dados")
        tela_alterar_dados.resize(411, 351)
        tela_alterar_dados.setMaximumSize(411, 351)
        tela_alterar_dados.setMinimumSize(411, 351)
        tela_alterar_dados.setWindowTitle(u"Alterar Dados")
        icon = QIcon()
        icon.addFile(u"icones/icone_login.png", QSize(), QIcon.Normal, QIcon.Off)
        tela_alterar_dados.setWindowIcon(icon)
        self.centralwidget = QWidget(tela_alterar_dados)
        self.centralwidget.setObjectName(u"centralwidget")
        self.group_box_alterar = QGroupBox(self.centralwidget)
        self.group_box_alterar.setObjectName(u"group_box_alterar")
        self.group_box_alterar.setEnabled(True)
        self.group_box_alterar.setGeometry(QRect(20, 50, 371, 61))
        font = QFont()
        font.setPointSize(12)
        self.group_box_alterar.setFont(font)
        self.group_box_alterar.setTitle(u"Escolha o que deseja alterar")
        self.check_box_alterar_senha = QCheckBox(self.group_box_alterar)
        self.check_box_alterar_senha.setObjectName(u"check_box_alterar_senha")
        self.check_box_alterar_senha.setGeometry(QRect(10, 30, 70, 17))
        self.check_box_alterar_senha.setText(u"Senha")
        self.check_box_alterar_cargo = QCheckBox(self.group_box_alterar)
        self.check_box_alterar_cargo.setObjectName(u"check_box_alterar_cargo")
        self.check_box_alterar_cargo.setGeometry(QRect(140, 30, 70, 17))
        self.check_box_alterar_cargo.setText(u"Cargo")
        self.texto_matricula = QLineEdit(self.centralwidget)
        self.texto_matricula.setObjectName(u"texto_matricula")
        self.texto_matricula.setGeometry(QRect(130, 20, 261, 21))
        self.texto_matricula.setFont(font)
        self.texto_matricula.setText(u"")
        self.texto_matricula.setMaxLength(20)
        self.texto_matricula.setPlaceholderText(u"")
        self.label_matricula = QLabel(self.centralwidget)
        self.label_matricula.setObjectName(u"label_matricula")
        self.label_matricula.setGeometry(QRect(20, 20, 71, 16))
        self.label_matricula.setFont(font)
        self.label_matricula.setText(u"Matrícula:")
        self.group_box_alterar_cargo = QGroupBox(self.centralwidget)
        self.group_box_alterar_cargo.setObjectName(u"group_box_alterar_cargo")
        self.group_box_alterar_cargo.setEnabled(False)
        self.group_box_alterar_cargo.setGeometry(QRect(20, 120, 371, 61))
        self.group_box_alterar_cargo.setFont(font)
        self.group_box_alterar_cargo.setTitle(u"Alterar cargo")
        self.radio_button_vendedor = QRadioButton(self.group_box_alterar_cargo)
        self.radio_button_vendedor.setObjectName(u"radio_button_vendedor")
        self.radio_button_vendedor.setGeometry(QRect(10, 30, 91, 17))
        self.radio_button_vendedor.setText(u"Vendedor")
        self.radio_button_gerente = QRadioButton(self.group_box_alterar_cargo)
        self.radio_button_gerente.setObjectName(u"radio_button_gerente")
        self.radio_button_gerente.setGeometry(QRect(140, 30, 81, 17))
        self.radio_button_gerente.setText(u"Gerente")
        self.radio_button_entregador = QRadioButton(self.group_box_alterar_cargo)
        self.radio_button_entregador.setObjectName(u"radio_button_entregador")
        self.radio_button_entregador.setGeometry(QRect(250, 30, 101, 17))
        self.radio_button_entregador.setText(u"Entregador")
        self.group_box_senha = QGroupBox(self.centralwidget)
        self.group_box_senha.setObjectName(u"group_box_senha")
        self.group_box_senha.setEnabled(False)
        self.group_box_senha.setGeometry(QRect(20, 190, 371, 91))
        self.group_box_senha.setFont(font)
        self.group_box_senha.setTitle(u"Alterar senha")
        self.label_senha_2 = QLabel(self.group_box_senha)
        self.label_senha_2.setObjectName(u"label_senha_2")
        self.label_senha_2.setGeometry(QRect(10, 61, 131, 16))
        self.label_senha_2.setFont(font)
        self.label_senha_2.setText(u"Confirmar senha:")
        self.label_senha_1 = QLabel(self.group_box_senha)
        self.label_senha_1.setObjectName(u"label_senha_1")
        self.label_senha_1.setGeometry(QRect(10, 30, 61, 16))
        self.label_senha_1.setFont(font)
        self.label_senha_1.setText(u"Senha:")
        self.texto_senha_1 = QLineEdit(self.group_box_senha)
        self.texto_senha_1.setObjectName(u"texto_senha_1")
        self.texto_senha_1.setGeometry(QRect(150, 29, 211, 21))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setStrikeOut(False)
        font1.setKerning(True)
        font1.setStyleStrategy(QFont.PreferDefault)
        self.texto_senha_1.setFont(font1)
        self.texto_senha_1.setText(u"")
        self.texto_senha_1.setMaxLength(20)
        self.texto_senha_1.setEchoMode(QLineEdit.Password)
        self.texto_senha_1.setPlaceholderText(u"")
        self.texto_senha_2 = QLineEdit(self.group_box_senha)
        self.texto_senha_2.setObjectName(u"texto_senha_2")
        self.texto_senha_2.setGeometry(QRect(150, 60, 211, 21))
        self.texto_senha_2.setFont(font1)
        self.texto_senha_2.setText(u"")
        self.texto_senha_2.setMaxLength(20)
        self.texto_senha_2.setEchoMode(QLineEdit.Password)
        self.texto_senha_2.setPlaceholderText(u"")
        self.botao_alterar = QPushButton(self.centralwidget)
        self.botao_alterar.setObjectName(u"botao_alterar")
        self.botao_alterar.setGeometry(QRect(130, 290, 141, 41))
        self.botao_alterar.setFont(font)
        self.botao_alterar.setText(u"Alterar dados")
        tela_alterar_dados.setCentralWidget(self.centralwidget)
        QMetaObject.connectSlotsByName(tela_alterar_dados)
    # setupUi


class CriarTelaAlterarDados(QtWidgets.QMainWindow, Ui_tela_alterar_dados):
    def __init__(self):
        super(CriarTelaAlterarDados, self).__init__()
        self.setupUi(self)