from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
from PySide2 import QtWidgets


class Ui_tela_cadastrar_produto(object):
    def setupUi(self, tela_cadastrar_produto):
        if not tela_cadastrar_produto.objectName():
            tela_cadastrar_produto.setObjectName(u"tela_cadastrar_produto")
        tela_cadastrar_produto.resize(404, 279)
        tela_cadastrar_produto.setMaximumSize(404, 279)
        tela_cadastrar_produto.setMinimumSize(404, 279)
        tela_cadastrar_produto.setWindowTitle(u"Cadastrar Produto")
        icon = QIcon()
        icon.addFile(u"icones/icone_produto.png", QSize(), QIcon.Normal, QIcon.Off)
        tela_cadastrar_produto.setWindowIcon(icon)
        tela_cadastrar_produto.setWindowFilePath(u"")
        self.label_descricao = QLabel(tela_cadastrar_produto)
        self.label_descricao.setObjectName(u"label_descricao")
        self.label_descricao.setGeometry(QRect(20, 20, 91, 21))
        font = QFont()
        font.setFamily(u"MS Shell Dlg 2")
        font.setPointSize(12)
        self.label_descricao.setFont(font)
        self.label_descricao.setText(u"Descrição:")
        self.label_marca = QLabel(tela_cadastrar_produto)
        self.label_marca.setObjectName(u"label_marca")
        self.label_marca.setGeometry(QRect(20, 50, 91, 21))
        self.label_marca.setFont(font)
        self.label_marca.setText(u"Marca:")
        self.label_tamanho = QLabel(tela_cadastrar_produto)
        self.label_tamanho.setObjectName(u"label_tamanho")
        self.label_tamanho.setGeometry(QRect(20, 80, 91, 21))
        self.label_tamanho.setFont(font)
        self.label_tamanho.setText(u"Tamanho:")
        self.label_quantidade = QLabel(tela_cadastrar_produto)
        self.label_quantidade.setObjectName(u"label_quantidade")
        self.label_quantidade.setGeometry(QRect(20, 110, 91, 21))
        self.label_quantidade.setFont(font)
        self.label_quantidade.setText(u"Quantidade:")
        self.label_preco_compra = QLabel(tela_cadastrar_produto)
        self.label_preco_compra.setObjectName(u"label_preco_compra")
        self.label_preco_compra.setGeometry(QRect(20, 140, 131, 21))
        self.label_preco_compra.setFont(font)
        self.label_preco_compra.setText(u"Preço de compra:")
        self.label_preco_venda = QLabel(tela_cadastrar_produto)
        self.label_preco_venda.setObjectName(u"label_preco_venda")
        self.label_preco_venda.setGeometry(QRect(20, 170, 151, 21))
        self.label_preco_venda.setFont(font)
        self.label_preco_venda.setText(u"Preço de venda:")
        self.texto_descricao = QLineEdit(tela_cadastrar_produto)
        self.texto_descricao.setObjectName(u"texto_descricao")
        self.texto_descricao.setGeometry(QRect(160, 20, 221, 22))
        font1 = QFont()
        font1.setPointSize(12)
        self.texto_descricao.setFont(font1)
        self.texto_descricao.setText(u"")
        self.texto_descricao.setMaxLength(50)
        self.texto_marca = QLineEdit(tela_cadastrar_produto)
        self.texto_marca.setObjectName(u"texto_marca")
        self.texto_marca.setGeometry(QRect(160, 50, 221, 22))
        self.texto_marca.setFont(font1)
        self.texto_marca.setText(u"")
        self.texto_marca.setMaxLength(50)
        self.texto_tamanho = QLineEdit(tela_cadastrar_produto)
        self.texto_tamanho.setObjectName(u"texto_tamanho")
        self.texto_tamanho.setGeometry(QRect(160, 80, 221, 22))
        self.texto_tamanho.setFont(font1)
        self.texto_tamanho.setText(u"")
        self.texto_tamanho.setMaxLength(50)
        self.spin_box_quantidade = QSpinBox(tela_cadastrar_produto)
        self.spin_box_quantidade.setObjectName(u"spin_box_quantidade")
        self.spin_box_quantidade.setGeometry(QRect(160, 110, 91, 22))
        self.spin_box_quantidade.setFont(font1)
        self.spin_box_quantidade.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.spin_box_quantidade.setMaximum(99999)
        self.double_spin_box_preco_compra = QDoubleSpinBox(tela_cadastrar_produto)
        self.double_spin_box_preco_compra.setObjectName(u"double_spin_box_preco_compra")
        self.double_spin_box_preco_compra.setGeometry(QRect(160, 140, 91, 22))
        self.double_spin_box_preco_compra.setFont(font1)
        self.double_spin_box_preco_compra.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.double_spin_box_preco_compra.setMaximum(9999.99)
        self.double_spin_box_preco_venda = QDoubleSpinBox(tela_cadastrar_produto)
        self.double_spin_box_preco_venda.setObjectName(u"double_spin_box_preco_venda")
        self.double_spin_box_preco_venda.setGeometry(QRect(160, 170, 91, 22))
        self.double_spin_box_preco_venda.setFont(font1)
        self.double_spin_box_preco_venda.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.double_spin_box_preco_venda.setMaximum(9999.99)
        self.botao_cadastrar_produto = QPushButton(tela_cadastrar_produto)
        self.botao_cadastrar_produto.setObjectName(u"botao_cadastrar_produto")
        self.botao_cadastrar_produto.setGeometry(QRect(110, 220, 201, 41))
        self.botao_cadastrar_produto.setFont(font1)
        self.botao_cadastrar_produto.setText(u"Cadastrar Produto")

        QMetaObject.connectSlotsByName(tela_cadastrar_produto)
    # setupUi


class CriarTelaCadastrarProduto(QtWidgets.QMainWindow, Ui_tela_cadastrar_produto):
    def __init__(self):
        super(CriarTelaCadastrarProduto, self).__init__()
        self.setupUi(self)
